export const linkedinExperienceSource = 'https://www.linkedin.com/in/apoorvdarshan/details/experience/'

export const linkedinExperience = [
  {
    role: 'Developer',
    company: 'Extensions for Chrome',
    type: 'Self-employed',
    dates: 'Jul 2026 – Present',
    duration: '1 mo',
    summary: 'Self-employed; building browser extensions end-to-end.',
    description: ['Building and shipping browser extensions solo from idea to published extension.'],
  },
  {
    role: 'Developer',
    company: 'Google Play',
    type: 'Self-employed',
    dates: 'Apr 2026 – Present',
    duration: '4 mos',
    summary: 'Self-employed; shipping Android apps to Google Play.',
    description: ['Solo indie dev shipping Android apps end-to-end to Play Store.'],
  },
  {
    role: 'Developer',
    company: 'App Store',
    type: 'Self-employed',
    dates: 'Feb 2026 – Present',
    duration: '6 mos',
    summary: 'Self-employed; shipping iOS apps to the App Store.',
    description: ['Indie dev building and shipping iOS apps solo, from idea to launch.'],
  },
  {
    role: 'Full Stack Developer',
    company: 'XIRCLS',
    type: 'Internship',
    dates: 'Nov 2025 – Feb 2026',
    duration: '4 mos',
    location: 'Mumbai, Maharashtra, India · Remote',
    summary: 'Full-stack CRM development and project leadership for a five-intern team.',
    highlights: [
      'Built and stabilized end-to-end CRM features covering Leads, Accounts, Authentication, Reminders, and Interactions with full CRUD, pagination, filtering, soft delete, and restore.',
      'Integrated frontend and backend APIs, resolving schema mismatches, UUID handling issues, and authentication/authorization gaps.',
      'Fixed critical security and data integrity issues, including session cache leakage and ownership validation flaws.',
      'Implemented user-scoped uniqueness validation for leads and accounts (email, phone, website).',
      'Improved real-time UI updates and performance using React Query cache invalidation and optimized detail pages.',
      'Strengthened form validation and UX flows, including mandatory fields, auto tab-switching, and safer save actions.',
      'Enhanced frontend structure, environment configuration, and overall dashboard responsiveness.',
      'Served as project lead intern, coordinating tasks and reviewing work for a team of 5 interns.',
    ],
  },
  {
    role: 'AI Trainer',
    company: 'Soul AI',
    type: 'Part-time',
    dates: 'Apr 2025',
    duration: '1 mo',
    location: 'Hyderabad, Telangana, India · Remote',
    summary: 'Evaluated Gemini 2.5 Pro and ChatGPT-4o educational conversations for Project Ceres.',
    description: ['Evaluated educational conversations from Gemini 2.5 Pro (Experimental) and ChatGPT-4o under Project Ceres.'],
  },
  {
    role: 'AI Trainer',
    company: 'Outlier',
    type: 'Freelance',
    dates: 'Feb 2025 – Mar 2025',
    duration: '2 mos',
    location: 'San Francisco, California, United States · Remote',
    summary: 'Trained and evaluated multimodal AI systems across reasoning, tool use, and preference tasks.',
    highlights: [
      'Supervised AI function-calling processes and tool use in projects like Attenuation Stamp.',
      'Improved AI reasoning capabilities across multiple domains, including STEM and philosophy, in Mail Valley.',
      'Designed complex image-based questions to challenge AI models and analyzed responses in Mighty Moo.',
      'Conducted preference evaluations and ranked AI model outputs as part of Pro Evals.',
      'Developed the Gallon Hamster, a multi-discipline multimodal reasoning system (SFT Phase 2).',
      'Identified platform issues and provided critical feedback during Nanoparticle Baobab and Normal Sultan.',
    ],
  },
  {
    role: 'Content Creator',
    company: 'YouTube',
    dates: 'Nov 2019 – Dec 2024',
    duration: '5 yrs 2 mos',
    summary: 'Grew a monetized channel to 21,500+ subscribers before its 2024 acquisition.',
    description: [
      'Built and grew a YouTube channel (originally Mr Alpha Delta, later Tales Through Toons) from Nov 2019 to Dec 2024, organically reaching 21,500+ subscribers — crossed at age 19. Monetized via YouTube Partner Program.',
      'Channel was acquired by a private buyer in December 2024 and has since been rebranded to Lootwala UPI Deals under new ownership. (Channel link attached.)',
    ],
  },
]
